exclude: vendor/.*/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format
        'types_or': [c, c++]
        language: system
        args: [-Werror, -i, --style=file]
